version: '3.9'

services:
  ai-arcade-snake-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-arcade-snake:latest
    container_name: ai-arcade-snake-service
    ports:
      - '8099:8099'
    restart: unless-stopped
